import { ITableColumnsMeta } from "src/app/interfaces/shared/meta-table-items.interface";
import { IMediaPartnerData } from "../media-partner/media-partner.interface";


export const columns: ITableColumnsMeta[] = [
  { field: 'checkbox', title: 'All', width: 80 },
  { field: 'parent_organization', title: 'Parent Organization (Based on W9)', width: 170 },
  { field: 'parent_organization', title: 'Parent Organization (Based on W9)', width: 170 },
  { field: 'media_outlet', title: 'Media Outlet', width: 90 },
  { field: 'coverage', title: 'Coverage', width: 80 },
  { field: 'media_channel', title: 'Media Channel', width: 85 },
  { field: 'target_audience', title: 'Target Audience', width: 110 },
  { field: 'media_kit_upload', title: 'Media Kit Upload', width: 220 },
  { field: 'rate_card_upload', title: 'Rate Card Upload', width: 220 },
  { field: 'w9_upload', title: 'W9 Upload', width: 220 },
  { field: 'website', title: 'Website', width: 170 },
  { field: 'street_address', title: 'Street Address', width: 125 },
  { field: 'city', title: 'City', width: 100 },
  { field: 'state', title: 'State', width: 100 },
  { field: 'zip_code', title: 'Zip Code', width: 85 },
  { field: 'main_contact_name', title: 'Main Contact Name', width: 130 },
  { field: 'contact_position', title: 'Job Title', width: 115 },
  { field: 'email', title: 'Contact Email', width: 180 },
  { field: 'contact_phone', title: 'Contact Phone', width: 125 },
  { field: 'ownership_type', title: 'Ownership Type', width: 105 },
  { field: 'certification_upload', title: 'Certification Upload', width: 220 },
  { field: 'do_status', title: 'DO Status', width: 90 },
  { field: 'status', title: 'Status', width: 90 },
  { field: 'last_verified', title: 'Last Verified', width: 100 },
  { field: 'action', title: 'Action', width: 75 },
]

export const data: IMediaPartnerData[] = [
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: false,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: false,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: true,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
  {
    checkbox: false,
    uuid: 'rfgwtgwerv2314sdaf',
    parent_organization: 'ABS-CBN',
    media_outlet: 'TFC',
    coverage: 'National',
    media_channel: 'Print (P)',
    target_audience: 'Chinese (C)',
    media_kit_upload: 'Lorem_ipsum_dolor.pdf',
    rate_card_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    w9_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    website: 'example.com',
    street_address: '8889 Hogan St',
    city: 'New York',
    state: 'New York',
    zip_code: '00501',
    main_contact_name: 'Cameron Wright',
    contact_position: 'Manager',
    email: 'peter.hicks@example.com',
    contact_phone: '(220) 427-5077',
    ownership_type: 'Corporation',
    certification_upload: 'Lorem ipsum dolor sit amet consectetur.pdf',
    do_status: { key: 'active', value: 'Active' },
    status: { key: 'active', value: 'Active' },
    last_verified: '04/06/2023',
  },
]

// export const response: IMediaPartner = { columns, data }
